### ISSUE TITLE
Dupe with pillar wand

### ISSUE THREAD

**Issue by SlimeCody** [OmerBenGera/WildTools#1]
**censored**

**Comment by OmerBenGera** [comment]
Pillar wands are meant to break blocks, so I assume these are builder wands that were renamed to "Pillar" wands, right?

**Comment by SlimeCody** [comment]
You helped me set them up 6 months ago when I ran into an issue with them, but yes they are.

**Comment by BiGUNMAN** [comment]
Description: We believe a recent mcMMO update that has patched a memory leak broke compatibility with WildTools' Builder Wand (maybe related to block meta data). Here is a video showing the bug: https://youtu.be/p0wZCrSdxMI

We would greatly appreciate your help on this issue @OmerBenGera. We have consistently cooperated and provided detailed bug reports. Thank you.

**Comment by OmerBenGera** [comment]
> 
> 
> Description: We believe a recent mcMMO update that has patched a memory leak broke compatibility with WildTools' Builder Wand (maybe related to block meta data). Here is a video showing the bug: https://youtu.be/p0wZCrSdxMI
> 
> We would greatly appreciate your help on this issue @OmerBenGera. We have consistently cooperated and provided detailed bug reports. Thank you.

If you believe it's due to mcmmo, you can just remove the comparability with it in the config.
Are you able to replicate the issue with the same config but on a server with only WT installed?

**Comment by SlimeCody** [comment]
![image](https://user-images.githubusercontent.com/49579480/104071079-fece2380-51cd-11eb-8654-474edb281f89.png)

**Comment by OmerBenGera** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/49579480/104071079-fece2380-51cd-11eb-8654-474edb281f89.png)
> 
> Edit: tried removing mcmmo off the compatibility list and still had the same issue, I cannot replicate it on a server with just
> WildTools.
This error is probably causing the "dupe".
What version of mcmmo are you using?

**Comment by SlimeCody** [comment]
https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/updates
The latest version there

**Comment by OmerBenGera** [comment]
Hey, please contact me on Discord, I'll need a copy of latest mcmmo jar (the one that you use) so I can fix the compatibility issues

**Comment by OmerBenGera** [comment]
Build #6 will fix the error, let me know if it still occurs
