### ISSUE TITLE
Condense wand for netherite ingot is broken

### ISSUE THREAD

**Issue by JHarris12345** [OmerBenGera/WildTools#10]
So here is my condense wand for a netherite ingot on plugin version 2.10.4.

netherite_wand_unlmt:
    tool-mode: CRAFTING
    type: STICK
    unbreakable: true
    name: '&f --{ &9&lNetherite Wand &f}-- '
    lore:
    - '&8&m---------------------------------------'
    - '&7 Hit a chest to craft netherite ingots from'
    - '&7 gold ingots and netherite scrap inside!'
    - '&f'
    - '&9&l Uses:'
    - '&fUnlimited'
    - '&f'
    - '&8&m---------------------------------------'
    craftings:
    - NETHERITE_INGOT

As you can see this should condense netherite scrap and gold ingots into netherite ingots. Here is the chest BEFORE using the wand:
![image](https://user-images.githubusercontent.com/46936647/110190872-65ae3880-7e1d-11eb-8464-9dc976580ec4.png)

As you can see, you would expect after using the wand, 11 stacks of gold and 11 stacks of nethertite scrap should be used to form 172 netherite ingots and the remainder of the netherite scrap. However look at the after image:

![image](https://user-images.githubusercontent.com/46936647/110190897-89717e80-7e1d-11eb-887a-9a98a9b07a4b.png)

It forms the right amount of netherite ingots but uses all the netherite scrap for some reason

**Comment by OmerBenGera** [comment]
Use latest dev build, let me know if it still occurs

**Comment by OmerBenGera** [comment]
Hey, I uploaded a new dev build that fixes the issue (build 9) :)

**Comment by JHarris12345** [comment]
It works thanks but when will it get pushed to spigot as that hasnt been updated in ages and Im worried the next spigot updated wont include these changes?

**Comment by OmerBenGera** [comment]
Hey, I am gonna push updates to Spigot every month, and yes - this update will be pushed as well.

**Comment by JHarris12345** [comment]
Thanks
