### ISSUE TITLE
Builder Wands do not take durability damage and can be used as an infinite tool

### ISSUE THREAD

**Issue by Skizzles** [OmerBenGera/WildTools#15]
**Minecraft's Version**
1.16.5

**Plugin's Version**: -
Wildtools-b9.jar

**Describe the bug**
Builder wands allow for unlimited breaking as they do not take durability damage.

**To Reproduce**
Attempt to break blocks using a builder wand

**Additional information**
https://www.youtube.com/watch?v=3iTNurgVAdM

**Comment by OmerBenGera** [comment]
You can enable vanilla durability for that, which will fix this exact issue.
Look in the config for that option and enable it for you wands :)
