### ISSUE TITLE
Lands 

### ISSUE THREAD

**Issue by ZappySK** [OmerBenGera/WildTools#16]
Hey, I am using this plugin for lands https://www.spigotmc.org/resources/ultimate-lands-addon-for-%E2%9A%94-ultimate-clans-%E2%9A%94.88034/, and then I leave the land, and use 3x3 pickaxe, the blocks inside the land are broken, how to fix this?

**Comment by ZappySK** [comment]
![image](https://user-images.githubusercontent.com/76651966/112148217-ea4ed400-8bdd-11eb-85b9-8a5f749b4443.png)

**Comment by ZappySK** [comment]
He is outside my land, and he used pickaxe, and the blocks inside the lands were broken..

**Comment by ZappySK** [comment]
Ups.. i closed sorry

**Comment by OmerBenGera** [comment]
Add Lands to your claiming plugins in the config.

**Comment by ZappySK** [comment]
What you mean?

**Comment by OmerBenGera** [comment]
Open the config file of WildTools, and add "Lands" to the claiming plugins list there
