### ISSUE TITLE
Builder-Tool infinite durability

### ISSUE THREAD

**Issue by Faceless0102** [OmerBenGera/WildTools#3]
Hey!

So if you use a Builder Tool to chop down trees in an area where you can't place blocks, it doesn't use any durability.

**Comment by OmerBenGera** [comment]
Like you're using the builder wand (assuming it's an axe) for vanilla usage instead of it's intended behavior?

**Comment by Faceless0102** [comment]
Yeah

**Comment by OmerBenGera** [comment]
Have you tried enabling vanilla-damage for the tool?

**Comment by OmerBenGera** [comment]
Have you tried it?

**Comment by Faceless0102** [comment]
checking

**Comment by Faceless0102** [comment]
Works. Thanks!

**Comment by OmerBenGera** [comment]
Perfect :)
