### ISSUE TITLE
Durability, Enchanting, Renaming

### ISSUE THREAD

**Issue by Skizzles** [OmerBenGera/WildTools#5]
I know is another issue regarding the durability and being invincible for Builder tools.... but this is a bit more:

- Tools allow to be renamed with any renaming plugin
- Tools have infinite durability unless the proper action is done, this makes them invincible when using the opposite click action
- Tools can have enchants applied via an anvil so combined with the above makes an infinite tool

Wildtools b7
1.16.5
Purpur 1.16.5

**Comment by OmerBenGera** [comment]
About the first issue: How is it related to WildTools?
Custom renaming plugins aren't supported.

About the second & third issues - Have you tried enabling vanilla-damage for the tool?

**Comment by Skizzles** [comment]
Renaming them would break the tool, couldn't you block them from being renamed?

**Comment by Skizzles** [comment]
I enabled the vanilla damage and ye that does resolve the invincible part

**Comment by OmerBenGera** [comment]
> 
> 
> Renaming them would break the tool, couldn't you block them from being renamed?

I can't do that on my end. Also, renaming the tool will not break the tool if your rename plugin keeps all the nbt tags (it probably doesn't, which is not something I can fix as it just breaks the item)

**Comment by Skizzles** [comment]
all good then

**Comment by OmerBenGera** [comment]
I recommend contacting the developer of the renaming plugin, and ask them to add nbt support to the renamed item, so custom data saved for items will not be lost :)
I am closing this for now
