### ISSUE TITLE
Players can break worldguard protected regions with trench pickaxe

### ISSUE THREAD

**Issue by Projecki** [OmerBenGera/WildTools#8]
Hello,

WildTools 2.10.4. Spigot 1.16.5. Worldguard region has both build and block-break set to deny & WorldGuard is added as a claiming plugin in config.

**Comment by OmerBenGera** [comment]
Use latest dev build of WildTools and latest version of WorldGuard.
Let me know if it still occurs

**Comment by OmerBenGera** [comment]
Any news regarding this?
