### ISSUE TITLE
WildTools & Spartan combo isn't working out.

### ISSUE THREAD

**Issue by klaidoshka** [OmerBenGera/WildTools#9]
Hello, we're having WildTools for SellWand and Spartan as anti-cheat...             (( _NoCheatPlus isn't working! >:(_ ))

But Spartan doesn't load. It also has "compatibility" mode with WildTools, but enabling it doesn't help either.
Could something be done from your side maybe?

Error: https://pastebin.com/7Wn2QND4

Both plugins are using the latest version.
Server version: **Yatopia 1.16.5**

If not, it's okay, maybe we can find something else for SellWand 😅
Thanks for your answer!

**Comment by OmerBenGera** [comment]
Contact the Spartan developers regarding this, I have no clue what they're trying to do there.

**Comment by klaidoshka** [comment]
Thankies!

So, I have contacted the developer of Spartan anticheat, he said this...
`This has to do with their API
it's missing methods`

So in the end I have no clue, but if nothing can be done regarding this from your side or you don't have time for this (because of army stuff), I can just try switching to something different, no problem 🙌 ❤

**Comment by OmerBenGera** [comment]
There's nothing wrong with the API, and it doesn't miss any methods.
Not sure what compatibility they added, but they can just get rid of it...
